
services:
  # 1. Servizio API FastAPI (Il tuo modello in produzione)
  sentiment_api:
    # Istruisce Docker Compose a usare il Dockerfile in questa directory per costruire l'immagine
    build: .
    image: sentiment-analysis-api:local
    container_name: sentiment_api
    ports:
      # Mappa le porte per l'accesso all'API
      - "8000:8000"
    environment:
      # Variabile d'ambiente legata alla sicurezza dell'API
      - API_KEY=SUPER_SECRET_TOKEN_12345 
    # Label per permettere a Prometheus di scoprire e monitorare questo servizio
    labels:
      - prometheus.io/scrape=true
      - prometheus.io/port=8000
      - prometheus.io/path=/metrics

  # 2. Servizio Prometheus (Raccolta Metriche)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Interfaccia Prometheus
    volumes:
      # Monta il file di configurazione locale per dire a Prometheus cosa monitorare
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - sentiment_api # Avvia Prometheus dopo l'API

  # 3. Servizio Grafana (Visualizzazione dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Interfaccia Grafana
    environment:
      # Configurazioni di base per Grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      # Persistenza dei dati di Grafana
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus

  # 4. Servizio Jenkins (CI/CD)
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-cicd
    privileged: true
    user: root
    ports:
      - "8080:8080"    # Jenkins UI
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Accesso Docker host
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped


networks:
  monitoring:
    driver: bridge
  
volumes:
  jenkins_home:
    driver: local
  grafana-storage:
    driver: local
  prometheus-data:
  grafana-data:
